language: java
jdk:
- oraclejdk7
- oraclejdk8
after_success:
- mvn -e -X clean test jacoco:report coveralls:jacoco
env:
  global:
  - VERBOSE=1
  - secure: i9jW5TP+4Zih4PuLZbm0i8eHnDMDMTOr+CQhzlX7+xQDc8H8y5YGKMn4efffVsYrRubPoQDdRljFGyQE+cW7qYScvH+9QdbVqT2uc0/CiU4vjEdpB5qj5Z0g7bj05vaPiSdWe93fU/Bjf4tpNgA4Yoan9oUTU3Ii/hR4c0js6+E=
  - secure: Xylor/wHKbL3vvDNaSJdF6QrFdkGXG4Xb6L8u06Yhm1G+zLVErMmkW0N4wBRT3bqvI4WwevduGpumljcREIieoLhDjGDI/EHJLNDYC+3fefG8XDMy1acetNpbVAHIs9kpl8e20CWp13Ee/esPNMFsXie0NxTFgJaXAArY4AlEpY=
  - secure: jmuPc/868gO5IagJyFf/U300ILNbaaPNvH99jtxzE2Xs13GkzWL4JUdv+EYUX8xUJ0rlnSKA6oGxw2+ZCBG5yc8GF9qYYqHHFy5DiQleTI246B5+3zZVNBa5qfcZm6Pki+vN4VEJeTq0F2b1C8rmE2ofRKloLd7h+WLGy04+CcQ=

# force non-container build
sudo: required
# workaround for https://github.com/travis-ci/travis-ci/issues/5227
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
